version: '3.8'
services:
  db2:
    image: ibmcom/db2
    container_name: db2
    privileged: true
    ports:
      - "50000:50000"
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=password
    volumes:
      - db2data:/database

volumes:
  db2data:

